export default {
    item: [
        {value: 'item/_id', display: "Item Id"},
        {value: 'item/price', display: "Item Price"},
        {value: 'item/title', display: "Item title"},
        {value: 'item/sku', display: "Item SKU"},
        {value: 'item/__typename', display: "Type"},
        {value: 'created_at', display: "Created At"},
        {value: '_id', display: "Order Id"},
        {value: 'phone', display: "Order Phone"},
        {value: 'name', display: "Order Name"},
        {value: 'email', display: "Order Email"},
        {value: 'sub_total', display: "Order Subtotal"},
        {value: 'total', display: "Order Total"},
        {value: 'quantity', display: "Quantity"},
        {value: 'shipping', display: "Order Shipping Price"},
        {value: 'discount_value', display: "Order Discount Amount"},
        {value: 'fulfillment_status', display: "Order Fullfillment Status"},
        {value: 'financial_status', display: "Order Financial Status"},
        {value: 'customer/tags', display: "Customer Tags"},
        {value: 'billing_address/country', display: "Billing Country"},
        {value: 'billing_address/first_name', display: "Billing First Name"},
        {value: 'billing_address/last_name', display: "Billing Last Name"},
        {value: 'billing_address/line1', display: "Billing Address 1"},
        {value: 'billing_address/line2', display: "Billing Address 2"},
        {value: 'billing_address/city', display: "Billing City"},
        {value: 'billing_address/zip', display: "Billing ZIP"},
        {value: 'billing_address/state', display: "Billing Province"},
        {value: 'shipping_address/city', display: "Shipping City"},
        {value: 'shipping_address/line1', display: "Shipping Address 1"},
        {value: 'shipping_address/line2', display: "Shipping Address 2"},
        {value: 'shipping_address/zip', display: "Shipping ZIP"},
        {value: 'shipping_address/first_name', display: "Shipping First Name"},
        {value: 'shipping_address/last_name', display: "Shipping Last Name"},
        {value: 'shipping_address/country', display: "Shipping Country"},
        {value: 'shipping_address/state', display: "Shipping Province"},
    ],
    contact: [
        {value: 'id', display: 'Contact Id' },
        {value: 'email', display: 'Contact Email' },
        {value: 'phone', display: 'Contact Phone' },
        {value: 'first_name', display: 'Contact First Name' },
        {value: 'last_name', display: 'Contact Last Name' },
		{value: 'created_at', display: 'Created At'},
        {value: 'accepts_marketing', display: 'Accepts Marketing' },
        {value: 'address/country', display: 'Country' },
        {value: 'address/line1', display: 'Address 1' },
        {value: 'address/line2', display: 'Address 2' },
        {value: 'address/city', display: 'City' },
        {value: 'address/zip', display: 'ZIP' },
        {value: 'address/state', display: 'Province' },
        {value: 'address/email', display: 'Email' },
        {value: 'address/phone', display: 'Phone' },
        {value: 'address/first_name', display: 'Address First Name' },
        {value: 'address/last_name', display: 'Address Last Name' },
        {value: 'billing_address/country', display: 'Billing Country' },
        {value: 'billing_address/line1', display: 'Billing Address 1' },
        {value: 'billing_address/line2', display: 'Billing Address 2' },
        {value: 'billing_address/city', display: 'Billing City' },
        {value: 'billing_address/zip', display: 'Billig ZIP' },
        {value: 'billing_address/state', display: 'Billing Province' },
        {value: 'billing_address/email', display: 'Billing Email' },
        {value: 'billing_address/phone', display: 'Billing Phone' },
        {value: 'billing_address/first_name', display: 'Billing First Name' },
        {value: 'billing_address/last_name', display: 'Billing Last Name' }

    ]
}